<div>
          <table>
            <thead>
              <th>
                Id
              </th>
              <th>
                Nome
              </th>
              <th>
                Idade
              </th>
              <th>
                Email
              </th>
              <th>
                Telefone
              </th>
            </thead>
            <tbody>
              <tr>
                15420
              </tr>
              <tr>
                Rayanne
              </tr>
            </tbody>
          </table>
        </div>